//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4332Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazi
    {
        public int ID { get; set; }
        public string Kod_Zakaza { get; set; }
        public string data_cozdaniya { get; set; }
        public string vremya_zakaza { get; set; }
        public int kod_clienta { get; set; }
        public string uslugi { get; set; }
        public string status { get; set; }
        public string data_zakritiya { get; set; }
        public string vremya_prokata { get; set; }
    }
}
